import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    en: {
        dashboard: "Dashboard",
        interactions: "Interactions",
        profile: "Profile",
        settings: "Settings",
        logout: "Logout",
        login: "Login",
        register: "Register",
        contact: "Contact",
        medical_info: "Medical Info",
        medications: "My Medications",
        search: "Search",
        edit: "Edit",
        save: "Save",
        scans: "Total Scans",
        risk: "Risk Summary",
        trends: "Interaction Trends",
        protected: "Medora Protected",
        support_mode: "Pharmacist Support Mode",
        welcome: "Welcome back",
        pharmacist: "Pharmacist",
        patient: "Patient",
        blood_type: "Blood Type",
        allergies: "Allergies",
        conditions: "Conditions",
        emergency: "Emergency Contact",
        phone: "Phone",
        email: "Email",
        wilaya: "Wilaya",
        address: "Address",
        search_drug: "Search clinical data...",
        run_analysis: "Run Clinical Analysis",
        home: "Home",
        about: "About Us",
        my_meds_desc: "Long-term prescriptions saved to your profile",
        add_med: "Add Medication",
        saved: "saved",
        protected_desc: "New prescriptions are automatically cross-checked against your saved profile for clinical safety.",
        loading_profile: "Loading your profile...",
        not_set: "Not set",
        yrs: "yrs",
        blood_type_label: "BLOOD TYPE",
        allergies_label: "ALLERGIES",
        conditions_label: "CONDITIONS",
        emergency_label: "EMERGENCY CONTACT",
        phone_label: "PHONE",
        email_label: "EMAIL",
        wilaya_label: "WILAYA",
        address_label: "ADDRESS",
        clinicalDashboard: "Clinical Dashboard",
        realTimeAnalytics: "Real-time analytics and medication safety metrics",
        launchPharmacistMode: "Launch Pharmacist Mode",
        totalScans: "Total Scans",
        criticalAlerts: "Critical Alerts",
        activePharmacists: "Active Pharmacists",
        databaseStatus: "Database Status",
        live: "Live",
        stable: "Stable",
        vsLastWeek: "vs last week",
        interactionTrends: "Interaction Trends",
        interactionTrends: "Interaction Trends",
        scanVolumeDescription: "Scan volume and detected clinical risks across all stations",
        hero_title: "Check your medications before they clash",
        hero_desc: "Medora checks drug interactions against 236,000+ clinical records and explains results in Algerian Darija — so every patient and pharmacist can understand.",
        try_medora: "Try Medora",
        effortless_safety: "Making Prescription Safety Effortless.",
        seamless_exp: "Using Medora is a seamless, guided experience designed to make medication checking simple, accurate, and accessible for everyone.",
        step1_title: "Input Medications",
        step1_desc: "Type the names of your drugs manually, or simply upload a photo of your prescription.",
        step2_title: "Smart Extraction",
        step2_desc: "Our OCR engine automatically reads and extracts the exact medication names instantly.",
        step3_title: "Clinical Verification",
        step3_desc: "Your list is cross-referenced against DDInter's 236,000+ verified interaction records.",
        step4_title: "Clear Results",
        step4_desc: "Warnings are translated into plain Algerian Darija so anyone can understand the risks.",
        intel_safety: "Built for Everyone Who Touches a Prescription",
        intel_safety_desc: "Whether you're a patient managing daily medications, a pharmacist at the counter, or a health authority tracking outcomes — Medora gives you a reason to feel safer.",
        card_patients_title: "For Patients",
        card_patients_1: "Explanations you can actually understand, in your own dialect, at no cost.",
        card_patients_2: "A medication profile that grows with you and automatically alerts you to risks with every new prescription.",
        card_pharm_title: "For Pharmacists",
        card_pharm_1: "A professional tool that reinforces your advisory role at the dispensing counter.",
        card_pharm_2: "Reduced liability exposure: every interaction check is logged and structured.",
        card_pharm_3: "A dashboard that helps you manage multiple patients and export interaction reports for patient files.",
        card_system_title: "For the Healthcare System",
        card_system_1: "A reduction in preventable hospitalizations linked to drug interactions — a significant and measurable cost to public hospitals.",
        card_system_2: "Anonymized, aggregated community data on adverse reactions by wilaya — actionable intelligence for health authorities and the ANPP.",
        testimonials_title: "What our professionals say",
        dr_amina_quote: "Medora has completely transformed how we verify prescriptions. The Darija translations make it incredibly easy to explain complex interactions.",
        ready_to_verify: "Ready to verify your medications?",
        join_thousands: "Join thousands of healthcare professionals and patients who trust Medora.",
        create_account: "Create Account",
        reach_out: "Reach Out to Us",
        full_name: "Full Name",
        email_addr: "Email Address",
        phone_num: "Phone Number",
        how_can_help: "How can we help you?",
        submit_req: "Submit Request",
        privacy_terms: "Privacy Policy and Term of Use",
        about_story_badge: "Our Story",
        about_empower_title: "Empowering medication Safety.",
        about_medora_desc: "Medora is more than just a platform—it's a bridge between complex medical data and patient safety.",
        about_mission_title: "Our Mission",
        about_mission_desc: "Medora was founded with a singular focus: to modernize how drug interactions are handled in Algeria.",
        about_vision_title: "Our Vision",
        about_vision_desc: "To become the definitive medical safety launchpad for Algeria, ensuring every patient has a clear path to health excellence.",
        inter_title: "Clinical Interaction Analysis.",
        inter_desc: "Cross-reference patient medication regimens against over 236,000 clinical records.",
        real_time_sync: "Real-time Sync",
        ddinter_verified: "DDInter Verified",
        multi_lingual: "Multi-Lingual",
        add_meds: "Add Medications",
        search_generic: "Search by generic or brand name",
        search_placeholder: "Search e.g. Doliprane...",
        suggestions: "Suggestions",
        selected_drugs: "Selected Drugs",
        no_drugs: "No drugs added yet",
        analyzing: "Analyzing...",
        analyze_btn: "Analyze Interactions",
        clinical_note: "Clinical Note:",
        disclaimer: "This tool uses the DDInter database. Results are for information only. Always consult a doctor.",
        analysis_engine: "Interaction Analysis Engine",
        engine_desc: "Search and select at least two medications to evaluate their potential clinical interactions.",
        major_inter: "Major Interaction",
        moderate_inter: "Moderate Interaction",
        minor_inter: "Minor Interaction",
        scanning_db: "Scanning DDInter...",
        analysis_results: "Analysis Results",
        pairs_analyzed: "pairs analyzed",
        report_incident: "Report Incident"
    },
    fr: {
        dashboard: "Tableau de bord",
        interactions: "Interactions",
        profile: "Profil",
        settings: "Paramètres",
        logout: "Déconnexion",
        login: "Connexion",
        register: "S'inscrire",
        contact: "Contact",
        medical_info: "Infos Médicales",
        medications: "Mes Médicaments",
        search: "Rechercher",
        edit: "Modifier",
        save: "Enregistrer",
        scans: "Total des scans",
        risk: "Résumé des risques",
        trends: "Tendances d'interaction",
        protected: "Medora Protégé",
        support_mode: "Mode Support Pharmacien",
        welcome: "Bon retour",
        pharmacist: "Pharmacien",
        patient: "Patient",
        blood_type: "Groupe Sanguin",
        allergies: "Allergies",
        conditions: "Pathologies",
        emergency: "Contact d'urgence",
        phone: "Téléphone",
        email: "E-mail",
        wilaya: "Wilaya",
        address: "Adresse",
        search_drug: "Rechercher des données...",
        run_analysis: "Lancer l'analyse",
        home: "Accueil",
        about: "À Propos",
        my_meds_desc: "Prescriptions à long terme enregistrées dans votre profil",
        add_med: "Ajouter un Médicament",
        saved: "enregistrés",
        protected_desc: "Les nouvelles prescriptions sont automatiquement vérifiées par rapport à votre profil.",
        loading_profile: "Chargement de votre profil...",
        not_set: "Non défini",
        yrs: "ans",
        blood_type_label: "GROUPE SANGUIN",
        allergies_label: "ALLERGIES",
        conditions_label: "PATHOLOGIES",
        emergency_label: "CONTACT D'URGENCE",
        phone_label: "TÉLÉPHONE",
        email_label: "E-MAIL",
        wilaya_label: "WILAYA",
        address_label: "ADRESSE",
        clinicalDashboard: "Tableau Clinique",
        realTimeAnalytics: "Analyses en temps réel et métriques de sécurité",
        launchPharmacistMode: "Mode Pharmacien",
        totalScans: "Total des Scans",
        criticalAlerts: "Alertes Critiques",
        activePharmacists: "Pharmaciens Actifs",
        databaseStatus: "Statut Base de Données",
        live: "En direct",
        stable: "Stable",
        vsLastWeek: "vs semaine dernière",
        interactionTrends: "Tendances d'Interaction",
        interactionTrends: "Tendances d'Interaction",
        scanVolumeDescription: "Volume de scans et risques cliniques détectés",
        hero_title: "Vérifiez vos médicaments avant qu'ils ne s'entrechoquent",
        hero_desc: "Medora vérifie les interactions médicamenteuses parmi 236 000+ dossiers cliniques et explique les résultats en Darija algérienne.",
        try_medora: "Essayer Medora",
        effortless_safety: "La sécurité des prescriptions sans effort.",
        seamless_exp: "Medora est une expérience fluide conçue pour rendre la vérification simple, précise et accessible à tous.",
        step1_title: "Saisie des Médicaments",
        step1_desc: "Tapez les noms manuellement ou téléchargez simplement une photo de votre ordonnance.",
        step2_title: "Extraction Intelligente",
        step2_desc: "Notre moteur OCR lit et extrait instantanément les noms exacts des médicaments.",
        step3_title: "Vérification Clinique",
        step3_desc: "Votre liste est croisée avec 236 000+ enregistrements vérifiés de DDInter.",
        step4_title: "Résultats Clairs",
        step4_desc: "Les avertissements sont traduits en Darija pour que tout le monde comprenne les risques.",
        intel_safety: "Conçu pour tous ceux qui touchent une ordonnance",
        intel_safety_desc: "Que vous soyez un patient gérant ses médicaments quotidiens, un pharmacien au comptoir, ou une autorité de santé — Medora vous donne une raison de vous sentir plus en sécurité.",
        card_patients_title: "Pour les Patients",
        card_patients_1: "Des explications compréhensibles, dans votre propre dialecte, gratuitement.",
        card_patients_2: "Un profil médicamenteux qui évolue avec vous et vous alerte automatiquement des risques à chaque nouvelle ordonnance.",
        card_pharm_title: "Pour les Pharmaciens",
        card_pharm_1: "Un outil professionnel qui renforce votre rôle de conseil au comptoir de dispensation.",
        card_pharm_2: "Réduction de l'exposition à la responsabilité : chaque vérification d'interaction est journalisée et structurée.",
        card_pharm_3: "Un tableau de bord pour gérer plusieurs patients et exporter les rapports d'interactions pour les dossiers patients.",
        card_system_title: "Pour le Système de Santé",
        card_system_1: "Une réduction des hospitalisations évitables liées aux interactions médicamenteuses — un coût significatif et mesurable pour les hôpitaux publics.",
        card_system_2: "Des données communautaires anonymisées et agrégées sur les réactions indésirables par wilaya — une intelligence actionnable pour les autorités sanitaires et l'ANPP.",
        testimonials_title: "Ce que disent nos professionnels",
        dr_amina_quote: "Medora a complètement transformé notre façon de vérifier les ordonnances. Les traductions en Darija facilitent l'explication.",
        ready_to_verify: "Prêt à vérifier vos médicaments ?",
        join_thousands: "Rejoignez des milliers de professionnels et de patients qui font confiance à Medora.",
        create_account: "Créer un compte",
        reach_out: "Contactez-nous",
        full_name: "Nom Complet",
        email_addr: "Adresse E-mail",
        phone_num: "Numéro de Téléphone",
        how_can_help: "Comment pouvons-nous vous aider ?",
        submit_req: "Envoyer la Demande",
        privacy_terms: "Politique de Confidentialité et Conditions d'Utilisation",
        about_story_badge: "Notre Histoire",
        about_empower_title: "Renforcer la sécurité des médicaments.",
        about_medora_desc: "Medora est plus qu'une plateforme — c'est un pont entre les données médicales complexes et la sécurité des patients.",
        about_mission_title: "Notre Mission",
        about_mission_desc: "Medora a été fondée avec un objectif unique : moderniser la gestion des interactions médicamenteuses en Algérie.",
        about_vision_title: "Notre Vision",
        about_vision_desc: "Devenir le tremplin définitif de la sécurité médicale en Algérie, garantissant à chaque patient un chemin clair vers l'excellence.",
        inter_title: "Analyse des Interactions Cliniques.",
        inter_desc: "Vérifiez les schémas thérapeutiques par rapport à 236 000+ dossiers cliniques.",
        real_time_sync: "Sync en temps réel",
        ddinter_verified: "Vérifié DDInter",
        multi_lingual: "Multi-langue",
        add_meds: "Ajouter des Médicaments",
        search_generic: "Recherche par nom générique ou commercial",
        search_placeholder: "Rechercher ex: Doliprane...",
        suggestions: "Suggestions",
        selected_drugs: "Médicaments Sélectionnés",
        no_drugs: "Aucun médicament ajouté",
        analyzing: "Analyse en cours...",
        analyze_btn: "Analyser les Interactions",
        clinical_note: "Note Clinique :",
        disclaimer: "Cet outil utilise la base DDInter. Les résultats sont informatifs. Consultez un médecin.",
        analysis_engine: "Moteur d'Analyse d'Interactions",
        engine_desc: "Sélectionnez au moins deux médicaments pour évaluer leurs interactions cliniques.",
        major_inter: "Interaction Majeure",
        moderate_inter: "Interaction Modérée",
        minor_inter: "Interaction Mineure",
        scanning_db: "Scan de DDInter...",
        analysis_results: "Résultats de l'Analyse",
        pairs_analyzed: "paires analysées",
        report_incident: "Signaler un Incident"
    },
    ar: {
        dashboard: "لوحة التحكم",
        interactions: "التفاعلات",
        profile: "الملف الشخصي",
        settings: "الإعدادات",
        logout: "تسجيل الخروج",
        login: "تسجيل الدخول",
        register: "إنشاء حساب",
        contact: "اتصال",
        medical_info: "معلومات طبية",
        medications: "أدويتي",
        search: "بحث",
        edit: "تعديل",
        save: "حفظ",
        scans: "إجمالي المسوحات",
        risk: "ملخص المخاطر",
        trends: "اتجاهات التفاعل",
        protected: "Medora محمي بـ",
        support_mode: "وضع دعم الصيدلي",
        welcome: "مرحباً بعودتك",
        pharmacist: "صيدلي",
        patient: "مريض",
        blood_type: "فصيلة الدم",
        allergies: "الحساسية",
        conditions: "الحالات الصحية",
        emergency: "جهة اتصال الطوارئ",
        phone: "الهاتف",
        email: "البريد الإلكتروني",
        wilaya: "الولاية",
        address: "العنوان",
        search_drug: "البحث في البيانات...",
        run_analysis: "إجراء تحليل سريري",
        home: "الرئيسية",
        about: "من نحن",
        my_meds_desc: "الوصفات الطبية طويلة الأمد المحفوظة في ملفك الشخصي",
        add_med: "إضافة دواء",
        saved: "محفوظ",
        protected_desc: "يتم فحص الوصفات الجديدة تلقائياً مقابل ملفك المحفوظ لضمان السلامة السريرية.",
        loading_profile: "جاري تحميل الملف الشخصي...",
        not_set: "غير محدد",
        yrs: "سنة",
        blood_type_label: "فصيلة الدم",
        allergies_label: "الحساسية",
        conditions_label: "الحالات الصحية",
        emergency_label: "اتصال الطوارئ",
        phone_label: "الهاتف",
        email_label: "البريد الإلكتروني",
        wilaya_label: "الولاية",
        address_label: "العنوان",
        clinicalDashboard: "لوحة التحكم السريرية",
        realTimeAnalytics: "تحليلات في الوقت الفعلي ومقاييس سلامة الأدوية",
        launchPharmacistMode: "تشغيل وضع الصيدلي",
        totalScans: "إجمالي المسوحات",
        criticalAlerts: "تنبيهات حرجة",
        activePharmacists: "الصيادلة النشطون",
        databaseStatus: "حالة قاعدة البيانات",
        live: "مباشر",
        stable: "مستقر",
        vsLastWeek: "مقارنة بالأسبوع الماضي",
        interactionTrends: "اتجاهات التفاعل",
        interactionTrends: "اتجاهات التفاعل",
        scanVolumeDescription: "حجم المسح والمخاطر السريرية المكتشفة",
        hero_title: "افحص أدويتك قبل أن تتعارض",
        hero_desc: "يقوم Medora بفحص تداخلات الأدوية مقابل أكثر من 236,000 سجل سريري ويشرح النتائج بالدارجة الجزائرية — ليفهمها كل مريض وصيدلي.",
        try_medora: "جرب Medora",
        effortless_safety: "جعل سلامة الوصفات الطبية أمراً سهلاً.",
        seamless_exp: "استخدام Medora تجربة سلسة وموجهة مصممة لجعل فحص الأدوية بسيطاً ودقيقاً ومتاحاً للجميع.",
        step1_title: "إدخال الأدوية",
        step1_desc: "اكتب أسماء أدويتك يدوياً، أو ببساطة ارفع صورة لوصفتك الطبية.",
        step2_title: "الاستخراج الذكي",
        step2_desc: "يقوم محرك OCR الخاص بنا بقراءة واستخراج أسماء الأدوية بدقة وفوراً.",
        step3_title: "التحقق السريري",
        step3_desc: "تتم مقاطعة قائمتك مع أكثر من 236,000 سجل تفاعل معتمد من DDInter.",
        step4_title: "نتائج واضحة",
        step4_desc: "يتم ترجمة التحذيرات إلى الدارجة الجزائرية البسيطة ليفهم الجميع المخاطر.",
        intel_safety: "مصمم لكل من يتعامل مع وصفة طبية",
        intel_safety_desc: "سواء كنت مريضاً يدير أدويته اليومية، أو صيدلياً في المنضدة، أو سلطة صحية تتابع النتائج — Medora يمنحك سبباً لتشعر بأمان أكبر.",
        card_patients_title: "للمرضى",
        card_patients_1: "شروحات يمكنك فهمها فعلاً، بلهجتك الخاصة، مجاناً.",
        card_patients_2: "ملف أدوية ينمو معك وينبهك تلقائياً للمخاطر مع كل وصفة جديدة.",
        card_pharm_title: "للصيادلة",
        card_pharm_1: "أداة مهنية تعزز دورك الاستشاري عند منضدة الصرف.",
        card_pharm_2: "تقليل التعرض للمسؤولية: كل فحص تفاعل مسجل ومنظم.",
        card_pharm_3: "لوحة تحكم تساعدك على إدارة عدة مرضى وتصدير تقارير التفاعلات لملفات المرضى.",
        card_system_title: "للمنظومة الصحية",
        card_system_1: "تقليل حالات الدخول للمستشفى الناتجة عن تفاعلات الأدوية — تكلفة كبيرة وقابلة للقياس على المستشفيات العمومية.",
        card_system_2: "بيانات مجتمعية مجهولة ومجمعة عن التفاعلات الدوائية حسب الولاية — معلومات استخباراتية قابلة للتنفيذ للسلطات الصحية والوكالة الوطنية.",
        testimonials_title: "ماذا يقول خبراؤنا",
        dr_amina_quote: "لقد غير Medora تماماً طريقة تحققنا من الوصفات الطبية. الترجمة بالدارجة تجعل من السهل جداً شرح التفاعلات المعقدة.",
        ready_to_verify: "هل أنت جاهز للتحقق من أدويتك؟",
        join_thousands: "انضم إلى الآلاف من المتخصصين في الرعاية الصحية والمرضى الذين يثقون في Medora.",
        create_account: "إنشاء حساب",
        reach_out: "اتصل بنا",
        full_name: "الاسم الكامل",
        email_addr: "البريد الإلكتروني",
        phone_num: "رقم الهاتف",
        how_can_help: "كيف يمكننا مساعدتك؟",
        submit_req: "إرسال الطلب",
        privacy_terms: "سياسة الخصوصية وشروط الاستخدام",
        about_story_badge: "قصتنا",
        about_empower_title: "تمكين سلامة الأدوية.",
        about_medora_desc: "مدورا أكثر من مجرد منصة - إنها جسر بين البيانات الطبية المعقدة وسلامة المرضى.",
        about_mission_title: "مهمتنا",
        about_mission_desc: "تأسست مدورا بتركيز واحد: تحديث كيفية التعامل مع تفاعلات الأدوية في الجزائر.",
        about_vision_title: "رؤيتنا",
        about_vision_desc: "أن نصبح نقطة الانطلاق النهائية للسلامة الطبية في الجزائر، لضمان حصول كل مريض على مسار واضح للصحة.",
        inter_title: "تحليل التفاعلات السريرية.",
        inter_desc: "مقارنة أنظمة الأدوية للمرضى مع أكثر من 236,000 سجل سريري.",
        real_time_sync: "مزامنة فورية",
        ddinter_verified: "معتمد من DDInter",
        multi_lingual: "متعدد اللغات",
        add_meds: "إضافة أدوية",
        search_generic: "البحث بالاسم التجاري أو العلمي",
        search_placeholder: "بحث مثلاً دوليبران...",
        suggestions: "اقتراحات",
        selected_drugs: "الأدوية المختارة",
        no_drugs: "لم يتم إضافة أدوية بعد",
        analyzing: "جاري التحليل...",
        analyze_btn: "تحليل التفاعلات",
        clinical_note: "ملاحظة سريرية:",
        disclaimer: "تستخدم هذه الأداة قاعدة بيانات DDInter. النتائج للاطلاع فقط. استشر الطبيب دائماً.",
        analysis_engine: "محرك تحليل التفاعلات",
        engine_desc: "ابحث واختر دواءين على الأقل لتقييم تفاعلاتهما السريرية المحتملة.",
        major_inter: "تفاعل خطير",
        moderate_inter: "تفاعل متوسط",
        minor_inter: "تفاعل طفيف",
        scanning_db: "جاري البحث في DDInter...",
        analysis_results: "نتائج التحليل",
        pairs_analyzed: "أزواج تم تحليلها",
        report_incident: "الإبلاغ عن حادثة"
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        return localStorage.getItem('Medora_lang') || 'en';
    });

    const t = (key) => {
        return translations[language][key] || key;
    };

    const changeLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('Medora_lang', lang);
        document.dir = lang === 'ar' ? 'rtl' : 'ltr';
    };

    useEffect(() => {
        const isAr = language === 'ar';
        document.dir = isAr ? 'rtl' : 'ltr';
        if (isAr) {
            document.body.classList.add('font-arabic');
        } else {
            document.body.classList.remove('font-arabic');
        }
    }, [language]);

    return (
        <LanguageContext.Provider value={{ language, t, changeLanguage }}>
            <div dir={language === 'ar' ? 'rtl' : 'ltr'} className={language === 'ar' ? 'font-arabic' : ''}>
                {children}
            </div>
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
